import type { ExpertProps } from "@/components/cards/card";

// Mock expert data
export const mockExperts: ExpertProps[] = [
  {
    id: "1",
    name: "Dr. Sarah Johnson",
    title: "Software Engineering Lead",
    category: "Engineering",
    rating: 4.9,
    reviews: 153,
    hourlyRate: 120,
    imageUrl:
      "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2340&q=80",
    availability: "Weekdays",
    specialties: ["System Architecture", "Cloud Infrastructure", "Leadership"],
  },
  {
    id: "2",
    name: "Michael Chen",
    title: "Senior Frontend Developer",
    category: "Development",
    rating: 4.8,
    reviews: 87,
    hourlyRate: 95,
    imageUrl:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2340&q=80",
    availability: "Evenings & Weekends",
    specialties: ["React", "UI/UX", "Performance Optimization"],
  },
  {
    id: "3",
    name: "Jessica Barnes",
    title: "Corporate Attorney",
    category: "Legal",
    rating: 4.7,
    reviews: 62,
    hourlyRate: 150,
    imageUrl:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1361&q=80",
    availability: "Mon, Wed, Fri",
    specialties: ["Contracts", "Intellectual Property", "Business Law"],
  },
  {
    id: "4",
    name: "Robert Kim",
    title: "Data Science Consultant",
    category: "Development",
    rating: 4.9,
    reviews: 115,
    hourlyRate: 135,
    imageUrl:
      "https://images.unsplash.com/photo-1531384441138-2736e62e0919?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80",
    availability: "Flexible",
    specialties: ["Machine Learning", "Big Data", "Analytics"],
  },
  {
    id: "5",
    name: "Olivia Rodriguez",
    title: "UX Research Specialist",
    category: "Design",
    rating: 4.6,
    reviews: 78,
    hourlyRate: 85,
    imageUrl:
      "https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1889&q=80",
    availability: "Tues, Thurs",
    specialties: ["User Testing", "Prototyping", "Information Architecture"],
  },
  {
    id: "6",
    name: "David Thomas",
    title: "Financial Advisor",
    category: "Finance",
    rating: 4.8,
    reviews: 93,
    hourlyRate: 110,
    imageUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80",
    availability: "Weekdays",
    specialties: ["Investment Planning", "Retirement", "Tax Strategy"],
  },
  {
    id: "7",
    name: "Emma Wilson",
    title: "Marketing Director",
    category: "Marketing",
    rating: 4.7,
    reviews: 108,
    hourlyRate: 130,
    imageUrl:
      "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80",
    availability: "Mon-Fri",
    specialties: ["Digital Strategy", "Brand Development", "Growth Marketing"],
  },
  {
    id: "8",
    name: "Dr. James Lee",
    title: "Healthcare Consultant",
    category: "Healthcare",
    rating: 4.9,
    reviews: 127,
    hourlyRate: 175,
    imageUrl:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    availability: "By Appointment",
    specialties: ["Hospital Operations", "Medical Technology", "Patient Care"],
  },
  {
    id: "9",
    name: "Alex Morgan",
    title: "Education Specialist",
    category: "Education",
    rating: 4.6,
    reviews: 91,
    hourlyRate: 80,
    imageUrl:
      "https://images.unsplash.com/photo-1629425733761-caae3b5f2e50?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80",
    availability: "Afternoons",
    specialties: [
      "Curriculum Development",
      "Online Learning",
      "Educational Psychology",
    ],
  },
  {
    id: "10",
    name: "Sophia Patel",
    title: "UX/UI Designer",
    category: "Design",
    rating: 4.8,
    reviews: 145,
    hourlyRate: 105,
    imageUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80",
    availability: "Weekdays",
    specialties: ["Product Design", "Interaction Design", "Design Systems"],
  },
];
